apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: nextcloud
spec:
  volumeName: nextcloud-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi