nextcloud:
  host: nextcloud.local
  trustedDomains:
    - nextcloud.local
    - nextcloud.nextcloud.svc.cluster.local
    - nextcloud.tusorihomelab.org
  existingSecret:
    enable: true
    secretName: nextcloud-admin-secret
    usernameKey: username
    passwordKey: password

phpClientHttpsFix:
  enabled: true
  protocol: https

internalDatabase:
  enabled: true

persistence:
  enabled: true
  storageClass: "-"
  existingClaim: nextcloud-pvc