apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: n8n-pvc
  name: n8n-pvc
  namespace: n8n
spec:
  storageClassName: ""
  volumeName: "n8n-pv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
