kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: n8n-postgresql-pvc
  namespace: n8n
spec:
  storageClassName: ""
  volumeName: "n8n-postgresql-pv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
