apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtts
  namespace: smart-home
spec:
  type: ClusterIP
  selector:
    app: mosquitto
  ports:
  - port: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-ws
  namespace: smart-home
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
  - port: 9001
    nodePort: 30083